--
-- Supabase Schema Initialization for a Personal Portfolio Web App (v3.1)
--
-- This script creates the necessary tables, seeds initial data, and sets up
-- a secure Role-Based Access Control (RBAC) system, including a dynamic
-- services table with currency support. This version corrects the RLS policy syntax.
--
-- Author: Eric
-- Date: October 28, 2025
--

-- 1. Table: gallery_items
--------------------------------------------------------------------------------
CREATE TABLE public.gallery_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    "imageUrl" text NOT NULL,
    "publicId" text NOT NULL,
    category text NOT NULL,
    CONSTRAINT gallery_items_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.gallery_items IS '''Stores portfolio gallery images and categories.''';

-- 2. Table: contacts
--------------------------------------------------------------------------------
CREATE TABLE public.contacts (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    email text NOT NULL,
    message text NOT NULL,
    CONSTRAINT contacts_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.contacts IS '''Stores messages submitted from the website contact form.''';

-- 3. Table: site_content
--------------------------------------------------------------------------------
CREATE TABLE public.site_content (
    content_key text NOT NULL,
    content_value text,
    CONSTRAINT site_content_pkey PRIMARY KEY (content_key)
);
COMMENT ON TABLE public.site_content IS '''Stores editable text content for various parts of the site.''';

-- 4. Table: services
--------------------------------------------------------------------------------
CREATE TABLE public.services (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    title text NOT NULL,
    price_min numeric NOT NULL,
    price_max numeric NOT NULL,
    currency text NOT NULL DEFAULT 'NGN', -- NGN or USD
    CONSTRAINT services_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.services IS '''Stores manageable service listings with currency options.''';

-- 5. Table: profiles
--------------------------------------------------------------------------------
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'user'
);
COMMENT ON TABLE public.profiles IS '''Stores user-specific data and roles for Role-Based Access Control.''';

-- 6. Insert Initial Data
--------------------------------------------------------------------------------
INSERT INTO public.site_content (content_key, content_value)
VALUES 
    ('about_me', 'I am a Product Designer, Video and Picture Editor, Writer, Junior Developer and lots more. Throughout my career, I have honed my skills in both print and digital designs, consistently delivering high-quality results that exceed client expectations. I have a keen eye for detail and a creative mindset that allows me to bring unique and innovative ideas to the table. Whether it’s designing a brand logo, creating a website layout, or developing a branding strategy, I am always up for the challenge or task. I look forward to the opportunity to discuss how my background, skills, and enthusiasm for creativity and design can contribute to your company''''s success.');

INSERT INTO public.services (title, price_min, price_max, currency)
VALUES
    ('Brand Packaging', 80, 8000, 'USD'),
    ('UI UX Design', 3000, 10000, 'USD'),
    ('Video Editing', 50, 5000, 'USD'),
    ('Coach Training', 100, 3000, 'USD');

-- 7. Automatic Profile Creation
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, role)
  VALUES (new.id, 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 8. Security Function for Role Checking
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION get_user_role()
RETURNS TEXT AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN 'anon';
  ELSE
    RETURN (
      SELECT role FROM public.profiles WHERE id = auth.uid()
    );
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9. Enable Row-Level Security (RLS) and Define Policies
--------------------------------------------------------------------------------

-- RLS for gallery_items
ALTER TABLE public.gallery_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view gallery items" ON public.gallery_items FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins can manage gallery items" ON public.gallery_items FOR ALL TO authenticated USING (get_user_role() = 'admin') WITH CHECK (get_user_role() = 'admin');

-- RLS for contacts
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can send contact messages" ON public.contacts FOR INSERT TO anon, authenticated WITH CHECK (true);

-- CORRECTED POLICIES FOR CONTACTS
CREATE POLICY "Admins can view contact messages"
ON public.contacts
FOR SELECT
TO authenticated
USING (get_user_role() = 'admin');

CREATE POLICY "Admins can delete contact messages"
ON public.contacts
FOR DELETE
TO authenticated
USING (get_user_role() = 'admin');

-- RLS for site_content
ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view site content" ON public.site_content FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins can insert site content"
ON public.site_content
FOR INSERT
TO authenticated
WITH CHECK (get_user_role() = 'admin');

CREATE POLICY "Admins can update site content"
ON public.site_content
FOR UPDATE
TO authenticated
USING (get_user_role() = 'admin')
WITH CHECK (get_user_role() = 'admin');

-- RLS for services
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view services" ON public.services FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins can manage services" ON public.services FOR ALL TO authenticated USING (get_user_role() = 'admin') WITH CHECK (get_user_role() = 'admin');

-- RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY "Admins can view all profiles" ON public.profiles FOR SELECT TO authenticated USING (get_user_role() = 'admin');

-- End of script