-- migrations/003_create_social_links.sql
--
-- Creates the social_links table and enables RLS.
--

-- 1. Create Table
CREATE TABLE public.social_links (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    platform text NOT NULL,
    url text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT social_links_pkey PRIMARY KEY (id),
    CONSTRAINT social_links_platform_unique UNIQUE (platform)
);

COMMENT ON TABLE public.social_links IS 'Stores social media platform links for the contact section.';

-- 2. Enable RLS
ALTER TABLE public.social_links ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
CREATE POLICY "Public can view social links" ON public.social_links FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins can manage social links" ON public.social_links FOR ALL TO authenticated USING (get_user_role() = 'admin') WITH CHECK (get_user_role() = 'admin');

-- 4. Seed Initial Data
INSERT INTO public.social_links (platform, url) VALUES
    ('Pinterest', 'https://pinterest.com/your-profile'),
    ('Upwork', 'https://upwork.com/freelancers/~your-profile'),
    ('YouTube', 'https://youtube.com/channel/your-channel-id');
